Repository NguyenVanViet2004/FE-GlowUp, pull requests merged in 2024-12, with the labels that each got.

#75 Duplicate header UI
  app/_layout.tsx
  app/about/AboutUs.tsx
  components/molecules/Checkout/PaymentMethodSection.tsx
  components/molecules/Date.tsx
  components/molecules/Time.tsx
  components/templates/ChangePasswordTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/SearchTemplate.tsx
  components/templates/ShowAllStylistTemplate.tsx
  components/templates/SpecialistTemplate.tsx
  constants/SettingListData.ts
  interfaces/Combo.ts
Labels: bug, FE-Task, UI-UX

#78 Resolve 'UI error occurred after merge #68'
  .vscode/settings.json
  app/_layout.tsx
  components/molecules/BookingUpcoming.tsx
  components/molecules/Checkout/ServiceInfoSection.tsx
  components/molecules/common/AppHeader.tsx
  components/molecules/common/RadioGroupItemWithLabel.tsx
  components/molecules/container/GradientScrollContainer.tsx
  components/templates/BookingConfirmationTemplate.tsx
  components/templates/BookingTemplate.tsx
  components/templates/ChangePasswordTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/SelectPaymentTemplate.tsx
  components/templates/SpecialistTemplate.tsx
  components/templates/WebviewTemplate.tsx
  package.json
  yarn.lock
Labels: bug

#81 Implement bank card info UI
  apis/HttpClient.ts
  app/_layout.tsx
  app/cardInfo/CardInfo.tsx
  app/index.tsx
  components/atoms/InputWithIcons.tsx
  components/molecules/BookingUpcoming.tsx
  components/molecules/Date.tsx
  components/molecules/SpecialComboCard.tsx
  components/molecules/payment/SelectPaymentItem.tsx
  components/organisms/StylistList.tsx
  components/templates/BookingConfirmationTemplate.tsx
  components/templates/ChangePasswordTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/ComboDetailTemplate.tsx
  components/templates/ProfileTemplate.tsx
  components/templates/SelectPaymentTemplate.tsx
  components/templates/ShowAllStylistTemplate.tsx
  components/templates/WebviewTemplate.tsx
  constants/SettingListData.ts
  features/userSlice.ts
  hooks/useFetchBank.ts
  interfaces/Appointment.ts
  interfaces/User.ts
  interfaces/enum/Status.ts
Labels: feature, UI-UX, FE-Test

#83 Add header to `webViewTemplate`
  app/cardInfo/CardInfo.tsx
  components/molecules/BookingCancelled.tsx
  components/molecules/BookingCompleted.tsx
  components/molecules/BookingUpcoming.tsx
  components/molecules/common/AppHeader.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/ComboDetailTemplate.tsx
  components/templates/ProfileTemplate.tsx
  components/templates/SelectPaymentTemplate.tsx
  components/templates/ShowAllStylistTemplate.tsx
  components/templates/WebviewTemplate.tsx
  features/userSlice.ts
Labels: feature, FE-Task, UI-UX

#86 Update the UI modal for app
  LICENSE.txt
  app/_layout.tsx
  components/molecules/BannerCombo.tsx
  components/molecules/BookingCancelled.tsx
  components/molecules/BookingCompleted.tsx
  components/molecules/BookingUpcoming.tsx
  components/molecules/common/AppModal.tsx
  components/organisms/NotificationList.tsx
  components/templates/ChangePasswordTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/HomeTemplate.tsx
  components/templates/ProfileTemplate.tsx
  components/templates/SelectPaymentTemplate.tsx
Labels: bug, feature, FE-Task, UI-UX

#84 Loading when data canceling booking
  components/molecules/BookingUpcoming.tsx
  components/molecules/Checkout/ServiceInfoSection.tsx
  components/molecules/Checkout/Summary.tsx
  components/molecules/common/AppModal.tsx
  components/molecules/common/RadioGroupItemWithLabel.tsx
  components/organisms/BookingList.tsx
  components/organisms/StepList.tsx
  components/templates/BookingConfirmationTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/ForgotPasswordTemplate.tsx
  components/templates/LoginTemplate.tsx
  components/templates/ProfileTemplate.tsx
  components/templates/ProfileUserTemplate.tsx
  components/templates/ResetPasswordTemplate.tsx
  components/templates/SelectPaymentTemplate.tsx
  components/templates/SignUpTemplate.tsx
  components/templates/SpecialistTemplate.tsx
  components/templates/VerifyOTPTemplate.tsx
  components/templates/WebviewTemplate.tsx
  hooks/useFetchAppointment.ts
  hooks/useNotifications.ts
  hooks/useUserLocation.ts
  interfaces/User.ts
Labels: bug, feature, UI-UX, Overdue

#89 Improve time picker compoennt for better user experience
  app/(tabs)/_layout.tsx
  app/_layout.tsx
  components/molecules/BookingUpcoming.tsx
  components/molecules/Checkout/PaymentMethodSection.tsx
  components/molecules/Date.tsx
  components/molecules/Time.tsx
  components/organisms/BookingList.tsx
  components/organisms/BookingMenuTabList.tsx
  components/templates/BookingTemplate.tsx
  components/templates/CheckoutTemplate.tsx
  components/templates/SearchTemplate.tsx
  components/templates/SpecialistTemplate.tsx
  components/templates/StepDetailsTemplate.tsx
  features/appModalSlice.ts
  hooks/useFetchAppointment.ts
  interfaces/enum/Status.ts
  redux/store.ts
Labels: feature, FE-Task, UI-UX
